### ISSUE TITLE
Grouping expand all does not work

### ISSUE THREAD

**Issue by masterkidan** [angular-ui/ng-grid#3051]
Just started trying out the grouping feature, and it looks like the expand all feature is not working. 

I was using the demo over here: http://ui-grid.info/docs/#/tutorial/209_grouping

It looks like the method is not defined: 
TypeError: undefined is not a function
    at Object.service.setAllNodes (http://ui-grid.info/release/ui-grid-unstable.js:16263:32)
    at Object.service.expandAllRows (http://ui-grid.info/release/ui-grid-unstable.js:16228:19)
    at Grid.publicApi.methods.grouping.expandAllRows (http://ui-grid.info/release/ui-grid-unstable.js:15702:27)
    at Object.expandAllRows (http://ui-grid.info/release/ui-grid-unstable.js:9027:27)
    at Scope.$scope.expandAll (app.js:29:29)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:10847:21
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular-touch.js:441:9
    at Scope.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:12702:28)
    at Scope.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:12800:23)
    at HTMLButtonElement.<anonymous> (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular-touch.js:440:13)

**Comment by PaulL1** [comment]
Yeah, I'm doing some work on it today, and I just noticed that this morning.  It was working, so I've changed something, but plan to fix it sometime today.

**Comment by masterkidan** [comment]
Out of curiosity isn't angular.forEach more performant? So why the change?

**Comment by PaulL1** [comment]
Standards compliance mainly.  I doubt there's much in it performance-wise, and I'd expect the native forEach in at least some browsers would be faster.

**Comment by mattaGIT** [comment]
This works around the issue

            $scope.gridApi.grid.registerDataChangeCallback(function() {
                if($scope.gridApi.grid.treeBase.tree instanceof Array){
                    $scope.gridApi.treeBase.expandAllRows();
                }
                
            });


The following works in every case I have tested. DataChangeCallback is called twice (for some unknown reason) on initial page load. The first time, gridApi.grid.treeBase.tree is an object which causes the issue with gridApi.grid.treeBase.tree.forEach above:

**Comment by PaulL1** [comment]
It may mean I initialised it with {} instead of [].  If you could find that code you could do a PR to fix it.
