### ISSUE TITLE
UI Grid Date Sorting issue

### ISSUE THREAD

**Issue by deepfriedbrain** [angular-ui/ng-grid#3518]
I cannot get date sorting to work correctly. I read in other threads that I need to convert the date (apparently coming in as string from the server) into a Date object. I wrote a filter to explicitly do the conversion to Date, but it still doesn't work. I have a plunkr to demonstrate the problem:

http://plnkr.co/edit/jKUENQj2bli4rL7jg9xm?p=preview

The error that I get is:
```
TypeError: a.getTime is not a function
    at d.sortDate (http://ui-grid.info/release/ui-grid-unstable.min.js:8:22419)
    at d.sort.k (http://ui-grid.info/release/ui-grid-unstable.min.js:8:23573)
    at Array.sort (native)
    at Object.d.sort (http://ui-grid.info/release/ui-grid-unstable.min.js:8:23664)
    at p.sortByColumn (http://ui-grid.info/release/ui-grid-unstable.min.js:7:19136)
    at c (http://ui-grid.info/release/ui-grid-unstable.min.js:7:13664)
    at http://ui-grid.info/release/ui-grid-unstable.min.js:7:13899
    at deferred.promise.then.wrappedCallback (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:11573:81)
    at deferred.promise.then.wrappedCallback (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:11573:81)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:11659:26(anonymous function) @ angular.js:10072$get @ angular.js:7364deferred.promise.then.wrappedCallback @ angular.js:11576deferred.promise.then.wrappedCallback @ angular.js:11573(anonymous function) @ angular.js:11659$get.Scope.$eval @ angular.js:12702$get.Scope.$digest @ angular.js:12514(anonymous function) @ angular.js:12740completeOutstandingRequest @ angular.js:4397(anonymous function) @ angular.js:4705
```

Can someone help me get the date sort to work? 

Thanks.

**Comment by PaulL1** [comment]
The main problem I see it that the sorting works on the underlying object, not on the filtered version.  Applying a filter isn't going to help, you need to actually change the value in your data.  In the edit tutorial we do this for the `registered` field: http://ui-grid.info/docs/#/tutorial/201_editable

**Comment by deepfriedbrain** [comment]
I don't know how I missed that because I did look at that tutorial before. Yes, it resolved the issue. I appreciate your quick response and great work!

Thank you.

**Comment by dabedur** [comment]
I ran into the same issue. It would be a really nice to have `rowSorter.sortDate` check to see if `a` and `b` are in fact date objects before trying to call `getTime()`. If `a` and `b` are strings, the sorting function could just reassign the values, e.g.,  `a = new Date(a)`, and `b = new Date(b)`. This makes the date sorting much more flexible and accommodating of string representations of dates - a format arguably more common to find in grids than proper JS Date objects.

I can open up a feature request if that is the proper channel to request something like this...

**Comment by PaulL1** [comment]
The best process would be to raise a pull request with your suggested code change.  We'd probably be supportive.

**Comment by AgDude** [comment]
This should be fixed by #3703

**Comment by boydwang** [comment]
How to handle the def like this：
 { field: "Time", displayName: "Time", type: 'date', cellFilter: 'date:"yyyy-MM-dd HH:mm:ss"' }

the new Data() works in Chrome but failed in IE, the IE will return a Nan for the "yyyy-MM-dd HH:mm:ss" format time string...

**Comment by AgDude** [comment]
@boydwang you need to make sure that your date string is formatted according to ISO 8601. https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations.  Note that some older version of safari may still have problems with parsing that.

**Comment by boydwang** [comment]
@AgDude thanks for your reply, I have solved it by myself.
