### ISSUE TITLE
uiGridCtrl.focus can be used before it's defined in some circumstances

### ISSUE THREAD

**Issue by rangoy** [angular-ui/ng-grid#3792]
Demo;

http://plnkr.co/edit/W2pUjR46y5sGHIIXewov?p=preview (based on demo of cellnav)

If the div containing the ui-grid with cell-nav activated is put within a ng-if, it will/might crash during init of ui-grid-cellnav with following exception. The same problem does not occur when using ng-show.

```
TypeError: uiGridCtrl.focus is not a function
    at module.directive.compile.post (http://ui-grid.info/release/ui-grid-unstable.js:13540:26)
    at nodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:6711:13)
    at delayedNodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:6933:11)
    at compositeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:6105:13)
    at nodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:6705:24)
    at delayedNodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:6933:11)
    at compositeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:6105:13)
    at compositeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:6108:13)
    at nodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:6705:24)
    at delayedNodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:6933:11) <div class="ui-grid-viewport ng-isolate-scope" ng-style="colContainer.getViewportStyle()" ui-grid-viewport="">
```

I think that the problem is that the focus() function is attached in uiGridViewport, which in some cases is not loaded before cellnav.

See commit aa56355469e0c2fe825f6c063bb2e2f7937817c7

**Comment by rangoy** [comment]
Sorry, seems like I've reported a duplicate of #3536
